### PR TITLE
Added support for deflated and base64 encoded valetudo maps

### PR DESCRIPTION
**Pull request by Hypfer**
This provides support for valetudo versions after and including commit https://github.com/Hypfer/Valetudo/commit/118705d4a98a3e41f29e5965a4bd757513926126

### CODE REVIEW

**Comment by zvldz** [comment]
@TheLastProject 
If you do not want to add minified JS, we can make a custom component for HA. Which will convert to old map format.
I even tried to do it through the jinja2 filters.

**Comment by TheLastProject** [comment]
@zvldz I mostly don't want to add minified JS to the source code because minified JS is practically binary. A custom component actually sounds like it could be a really good idea, that way we make it easier for other cards to also use the custom map instead of only supporting it for this card.

**Comment by zvldz** [comment]
Here is a custom component https://github.com/zvldz/homeassistant/tree/master/custom_components/custom_filters .
I have not yet uploaded to github as a separate project.
So far, this is just for testing, but it works for valetudo-dev.
Sensor:
```
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    json_attributes_template: "{{ value | decode_base64_and_inflate }}"
    name: xiaomi_map
    value_template: 'OK'
```

**Comment by Hypfer** [comment]
Maybe we could start building a custom Valetudo vacuum component instead of the vacuum.mqtt component 🤔

**Comment by TheLastProject** [comment]
I love your solution to it @zvldz, it's very clean. After you create your own repo for it I'd love a PR to update the README with instructions for 0.6.1.

**Comment by zvldz** [comment]
I may be able to make a template so that it is working for both the new and the old map format.

**Comment by zvldz** [comment]
universal sensor:
```
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    json_attributes_template: "{% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_base64_and_inflate }} {% endif %}"
    name: xiaomi_map
    value_template: 'OK'
```

**Comment by TheLastProject** [comment]
Well, almost universal. It doesn't deal with legacy mode :)

**Comment by zvldz** [comment]
I did not look at the new format in detail.
But it works with 0.6.1 and dev.

**Comment by zvldz** [comment]
I created a standalone repository https://github.com/zvldz/ha_custom_filters .
But I think it's too early to write the manual until the new version of Valetudo is not released.

I proposed one of the solutions for the migration to the new format.

**Comment by TheLastProject** [comment]
Well, a few people compile from source. We can add the instruction "for the development version of Valetudo" and I'll just update that sentence when that becomes a stable release :)

**Comment by zvldz** [comment]
Yes, I saw it. I will try to write instruction the other day.

**Comment by TheLastProject** [comment]
Closing this in favor of #72. Thanks to both of you :)

**Pull request closed without merging**
