### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rp86**
In response to issue #13, changes sensor configuration to use MQTT instead of REST.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Is it really this simple? This will work just like that? That's kinda cool.

I'd rather see this split into 2 parts though, especially because several people have stated being glad this card works without MQTT because it saves them another container.

How about first mentioning the MQTT solution, with links to how to set that up in Home Assistant and Valetudo, and then mentioning the REST API way, stating that Valetudo doesn't officially support that?

**Comment by rp86** [comment]
It does seem to work correctly, I was a bit surprised myself ;) Though I haven't checked that authentication still works as I don't use it myself.

I've update the readme as per your suggestions.

**Comment by TheLastProject** [comment]
Looking at the documentation for MQTT in Home Assistant, it doesn't look like authentication is supported: https://www.home-assistant.io/integrations/sensor.mqtt/

So let's remove those flags, put the authentication text back to the REST API and then I can hit merge :)

**Comment by TheLastProject** [comment]
Ping?

**Comment by rp86** [comment]
Sorry about the delay - file updated :)

**Comment by TheLastProject** [comment]
Thanks! :)

**Pull request merged**
